import { EnemyDataMap } from '../interfaces'
import { enemyWeapons } from './weapons'

export const enemies = {
  ant: {
    spawnPeriod: 100,
    speed: 100,
    health: 40,
    armor: 5,
    displaySize: 40,
    collisionSize: 35,
    bloodColor: 0x00dd00,
    color: 0x200505,
    walkAnimation: 'whiteant8',
    corpseImage: 'blood',
    corpseSize: 100,
    spriteSheetKey: 'whiteant8',
    randomSound: 'antsounds2',
    randomSoundVol: 2,
    randomSoundChance: 0.4,
    directionTimerMax: 750,
    directionTimerMin: 250,
    deathSound: 'antdeath',
    deathSoundVol: 1,
    hitDamage: 22,
    hitDelay: 500,
    hitSound: 'anthit',
    tooSmallToBleedWhenHit: true,
  },
  fireant: {
    spawnPeriod: 400,
    speed: 80,
    health: 200,
    armor: 10,
    displaySize: 60,
    collisionSize: 50,
    bloodColor: 0x00dd00,
    color: 0x770000,
    walkAnimation: 'whiteant8',
    corpseImage: 'blood',
    corpseSize: 200,
    spriteSheetKey: 'whiteant8',
    randomSound: 'antsounds2',
    randomSoundVol: 3,
    randomSoundChance: 0.4,
    directionTimerMax: 750,
    directionTimerMin: 250,
    deathSound: 'antdeath',
    deathSoundVol: 1.5,
    hitDamage: 22,
    hitDelay: 500,
    hitSound: 'anthit',
    tooSmallToBleedWhenHit: false,
    weapons: [enemyWeapons.enemyPlasmaSpit],
  },
} as EnemyDataMap
