import { EnemyDataMap } from '../interfaces'

export const enemies ={
    ant: {
      spawnPeriod: 25,
      speed: 100,
      health: 40,
      armor: 5,
      displaySize: 40,
      collisionSize: 35,
      bloodColor: 0x00dd00,
      color: 0x221111,
      walkAnimation: 'whiteant8',
      corpseImage: 'blood',
      corpseSize: 50,
      spriteSheetKey: 'whiteant8',
      randomSound: 'antsounds2',
      randomSoundVol: 1.5,
      randomSoundChance: 0.2,
      directionTimerMax: 750,
      directionTimerMin: 250,
      deathSound: 'antdeath',
      deathSoundVol: 0.6,
      hitDamage: 22,
      hitDelay: 500,
      hitSound: 'anthit',
      tooSmallToBleedWhenHit: true,
    },
    fireant: {
      spawnPeriod: 200,
      speed: 80,
      health: 200,
      armor: 10,
      displaySize: 60,
      collisionSize: 50,
      bloodColor: 0x00dd00,
      color: 0x770000,
      walkAnimation: 'whiteant8',
      corpseImage: 'blood',
      corpseSize: 100,
      spriteSheetKey: 'whiteant8',
      randomSound: 'antsounds2',
      randomSoundVol: 1.5,
      randomSoundChance: 0.2,
      directionTimerMax: 750,
      directionTimerMin: 250,
      deathSound: 'antdeath',
      deathSoundVol: 0.6,
      hitDamage: 22,
      hitDelay: 500,
      hitSound: 'anthit',
      tooSmallToBleedWhenHit: false,
    //   canFireProjectiles: true, // Indicates this enemy can fire projectiles
    //   fireRate: 1000, // Fire every second
    //   enemyWeapon: {
    //     image: 'enemyProjectile',
    //     damage: 10,
    //     initialSpeed: 200,
    //     trail: true, // Optionally add trail effects
    //   },
    },
  } as EnemyDataMap