import { WeaponSpec} from '../interfaces'

type WeaponDefinitions = { [key: string]: WeaponSpec }

export const weapons= {
    boltAP: {
      name: '40MM CANNON ARMOR PIERCING',
      fireDelay: 350,
      image: 'bullet1',
      initialSpeed: 1800,
      baseSpread: 0.03,
      roundHeight: 30,
      roundWidth: 4,
      damage: 25,
      penetration: 15,
      muzzleFlashSize: 3,
      totalAmmo: 400,
      magSize: 80,
      reloadDelay: 3000,
      fireSound: 'boltshot3',
      fireSoundVol: 1.4,
      fireAverageDetune: -200,
      fireDetuneRange: 100,
      reloadSound: 'hmgreload3',
      reloadSoundVol: 1,
      tracerRate: 1,
      tracerLightColor: 0xAAAAFF,
      tracerLightIntensity: 3,
      tracerProjectileColor: 0xAAAAFF,
      tracerLightRadius: 80,
      tracerScaleUp:1.5,
      tracerHitFadeTime: 0,
      tracerHitLightRadius: 0,
      tracerHitLightIntensity: 2.5,
  
      trail: true,
      trailDuration: 100,
      trailTint: 0xAAAAFF,
    },
    boltHE: {
    name: '40MM CANNON HIGH EXPLOSIVE',
      fireDelay: 300,
      image: 'bullet1',
      initialSpeed:750,
      baseSpread: 0.03,
      roundHeight: 20,
      roundWidth: 4,
      damage: 10,
      explodeRadius: 50,
      explodeDamage: 50,
      explodeSound: 'rocketexplosion',
      explodeSoundVol: 0.7,
      penetration: 0,
      muzzleFlashSize: 3,
      totalAmmo: 400,
      magSize: 80,
      reloadDelay: 3000,
      fireSound: 'boltshot4',
      fireSoundVol: 1.2,
      fireAverageDetune: -200,
      fireDetuneRange: 100,
      reloadSound: 'hmgreload3',
      reloadSoundVol: 1,
      tracerRate: 1,
      tracerLightColor: 0xFF5555,
      tracerLightIntensity: 1,
      tracerProjectileColor: 0xFF5555,
      tracerLightRadius: 80,
      tracerScaleUp:1.5,
      tracerHitFadeTime: 0,
      tracerHitLightRadius: 0,
      tracerHitLightIntensity: 2.5,
      detuneUpMax: 100,
      detuneDownMax: 100,
    },
    hmg1: {
      name: '12.7MM MACHINE GUN',
      fireDelay: 50,
      image: 'bullet1',
      initialSpeed: 700,
      baseSpread: 0.035,
      roundHeight: 25,
      roundWidth: 3,
      damage: 11,
      penetration: 6,
      muzzleFlashSize: 1.5,
      totalAmmo: 3200,
      magSize: 400,
      reloadDelay: 3000,
      fireSound: 'hmgshot2',
      fireSoundVol: 2.2,
      reloadSound: 'hmgreload3',
      reloadSoundVol: 1,
      tracerRate: 6,
      tracerLightColor: 0x880000,
      tracerLightIntensity: 5,
      tracerProjectileColor: 0x880000,
      tracerLightRadius: 80,
      tracerScaleUp:1.5,
      tracerHitFadeTime: 1500,
      tracerHitLightRadius: 100,
      tracerHitLightIntensity: 2.5
    },
    rockets1: {
      name: 'Hydra 84 ROCKET',
      fireDelay: 3000,
      image: 'missile',
      initialSpeed: 0,
      acceleration: 1000,
      maxSpeed: 2000,
      baseSpread: 0.1,
      roundHeight: 20,
      roundWidth: 10,
      damage: 0,
      explodeRadius: 70,
      explodeDamage: 65,
      explodeSound: 'rocketexplosion',
      explodeSoundVol: 1.3,
      penetration: 10,
      burstFire: 6,
      burstFireDelay: 100,
      hasBoostFlame: true,
      boosterLightColor: 0xed6240,
      boosterLightIntensity:3,
      boosterLightRadius: 100,
      muzzleFlashSize: 1.5,
      totalAmmo: 300,
      magSize: 30,
      reloadDelay: 5000,
      fireSound: 'rocketlaunch',
      fireSoundVol: 0.7,
      stopFireSoundOnHit: true,
      reloadSound: 'rocketsreload',
      reloadSoundVol: 1.3,
    },
    railgun1: {
      name: 'MK 43 DN-RAILGUN',
      fireDelay: 2000,
      image: 'bullet1',
      initialSpeed: 4000,
      baseSpread: 0.05,
      roundHeight: 80,
      roundWidth: 8,
      damage: 40,
      penetration: 70,
      tint: 0x7df9ff,
      lightColor: 0x7df9ff,
      lightIntensity: 1,
      muzzleFlashSize: 3,
      totalAmmo: 100,
      magSize: 1,
      reloadDelay: 2000,
      trail: true,
      trailDuration: 1000,
      fireSound: 'railgunshot',
      reloadSound: 'railgunreload3',
      reloadSoundVol: 1.4,
      tracerRate: 1,
      tracerLightColor: 0x2c75ff,
      tracerLightIntensity: 10,
      tracerProjectileColor: 0x2c75ff,
      tracerLightRadius: 150,
      tracerScaleUp:1,
      tracerHitFadeTime: 8000,
      tracerHitLightRadius: 70,
      tracerHitLightIntensity: 15
    },
  }  as WeaponDefinitions