import { WeaponSpec, EnemyWeaponSpec } from '../interfaces'

type WeaponsList = { [key: string]: WeaponSpec }
type EnemyWeaponsList = { [key: string]: EnemyWeaponSpec }

export const weapons = {
  beam1: {
    name: 'HG-NUCLEI PARTICLE BEAM',
    fireDelay: 10,
    image: '',
    initialSpeed: 0,
    baseSpread: 0,
    roundHeight: 0,
    roundWidth: 0,
    damage: 2.5, // dps: 250
    penetration: 0,
    totalAmmo: 10000,
    magSize: 10000,
    reloadDelay: 0,
    maxRange: 1000,
    fireSound: 'beamsound6',
    fireSoundVol: 2,
    reloadSound: '',
    isBeam: true,
    beamColor: 0xff0033,
    beamWidth: 1.5,
    beamGlowWidth: 15,
    beamGlowColor: 0xaa0000,
    beamParticlesDensity: 3,
    beamParticlesColor: 0xff0033,
    beamParticlesFadeTime: 300,
    beamLightRadius: 150,
    beamLightIntensity: 1,
    beamHitLightRadius: 100,
    beamHitLightIntensity: 0.5,
    terrainDamageMultiplier: 4
  },
  arc1: {
    name: 'CHANNELLED ARC CANNON',
    fireDelay: 30,
    image: '',
    initialSpeed: 0,
    baseSpread: 0,
    roundHeight: 0,
    roundWidth: 0,
    damage: 1.5, // dps: 50
    penetration: 0,
    totalAmmo: 3500,
    magSize: 3500,
    reloadDelay: 0,
    maxRange: 800,
    fireSound: 'lightning14',
    fireSoundVol: 1.5,
    reloadSound: '',
    isBeam: true,
    renderAsLightning: true,
    beamColor: 0x00ffff,
    beamWidth: 1,
    beamGlowWidth: 20,
    beamGlowColor: 0x0066ff,
    beamParticleInitialSize: 0.2,
    beamParticlesDensity: 3,
    beamParticlesColor: 0x00DDff,
    beamParticlesFadeTime: 1000,
    beamLightRadius: 150,
    beamLightIntensity: 0.8,
    beamHitLightRadius: 100,
    beamHitLightIntensity: 1.5,
    arcTargeting:true,
    arcTargetingAngle: 40,
    chaining: true,
    chainRange: 300,
    randomFlash: 0.005
  },
  boltAP: {
    name: '40MM CANNON ARMOR PIERCING',
    fireDelay: 250,
    image: 'bullet1',
    initialSpeed: 1800,
    baseSpread: 0.03,
    roundHeight: 30,
    roundWidth: 4,
    damage: 32, // dps: 128
    penetration: 15,
    muzzleFlashSize: 3,
    totalAmmo: 400,
    magSize: 80,
    reloadDelay: 3000,
    fireSound: 'boltshot3',
    fireSoundVol: 1.2,
    fireAverageDetune: -200,
    fireDetuneRange: 100,
    reloadSound: 'hmgreload3',
    reloadSoundVol: 1,
    tracerRate: 1,
    tracerLightColor: 0xaaaaff,
    tracerLightIntensity: 2,
    tracerProjectileColor: 0xaaaaff,
    tracerLightRadius: 80,
    tracerScaleUp: 1.5,
    tracerHitFadeTime: 0,
    tracerHitLightRadius: 0,
    tracerHitLightIntensity: 0,
    trail: true,
    trailDuration: 100,
    trailTint: 0xaaaaff,
  },
  boltHE: {
    name: '40MM CANNON HIGH EXPLOSIVE',
    fireDelay: 200,
    image: 'bullet1',
    initialSpeed: 1600,
    baseSpread: 0.03,
    roundHeight: 30,
    roundWidth: 4,
    damage: 5,
    explodeRadius: 50,
    explodeDamage: 60, // dps: 300
    explodeSound: 'rocketexplosion',
    explodeSoundVol: 0.7,
    penetration: 0,
    muzzleFlashSize: 3,
    totalAmmo: 560,
    magSize: 80,
    reloadDelay: 3000,
    fireSound: 'boltshot4',
    fireSoundVol: 1.2,
    fireAverageDetune: -200,
    fireDetuneRange: 100,
    reloadSound: 'hmgreload3',
    reloadSoundVol: 1,
    tracerRate: 1,
    tracerLightColor: 0xff5555,
    tracerLightIntensity: 2,
    tracerProjectileColor: 0xff5555,
    tracerLightRadius: 80,
    tracerScaleUp: 1.5,
    tracerHitFadeTime: 0,
    tracerHitLightRadius: 0,
    tracerHitLightIntensity: 0,
    terrainDamageMultiplier: 2
  },
  minigun1: {
    name: '12.7MM MINIGUN',
    fireDelay: 40,
    image: 'bullet1',
    initialSpeed: 1400,
    baseSpread: 0.08,
    roundHeight: 30,
    roundWidth: 3,
    damage: 12, // dps: 300
    penetration: 6,
    muzzleFlashSize: 1.5,
    totalAmmo: 6400,
    magSize: 400,
    reloadDelay: 3000,
    fireSound: 'minigunfire3',
    fireSoundVol: 2,
    reloadSound: 'hmgreload3',
    reloadSoundVol: 1,
    tracerRate: 6,
    tracerLightColor: 0xff3300,
    tracerLightIntensity: 5,
    tracerProjectileColor: 0xff3300,
    tracerLightRadius: 70,
    tracerScaleUp: 1.5,
    tracerHitFadeTime: 500,
    tracerHitLightRadius: 100,
    tracerHitLightIntensity: 2.5,
    repeatingContinuousFireSound: true,
  },
  rockets1: {
    name: 'Hydra 84 ROCKET',
    fireDelay: 3000,
    image: 'missile',
    initialSpeed: 0,
    acceleration: 1000,
    maxSpeed: 2000,
    baseSpread: 0.1,
    roundHeight: 20,
    roundWidth: 10,
    damage: 0,
    explodeRadius: 80,
    explodeDamage: 70,
    explodeSound: 'rocketexplosion',
    explodeSoundVol: 1.3,
    penetration: 10,
    burstFire: 6,
    burstFireDelay: 100,
    hasBoostFlame: true,
    boosterLightColor: 0xed6240,
    boosterLightIntensity: 3,
    boosterLightRadius: 100,
    muzzleFlashSize: 1.5,
    totalAmmo: 300,
    magSize: 30,
    reloadDelay: 5000,
    fireSound: 'rocketlaunch',
    fireSoundVol: 0.7,
    stopFireSoundOnHit: true,
    reloadSound: 'rocketsreload',
    reloadSoundVol: 1.3,
    terrainDamageMultiplier: 2
  },
  railgun1: {
    name: 'MK 43 DN-RAILGUN',
    fireDelay: 2000,
    image: 'bullet1',
    initialSpeed: 4000,
    baseSpread: 0.025,
    roundHeight: 80,
    roundWidth: 8,
    damage: 100, // dps: 50
    penetration: 100,
    tint: 0x7df9ff,
    lightColor: 0x7df9ff,
    lightIntensity: 1,
    muzzleFlashSize: 3,
    totalAmmo: 100,
    magSize: 1,
    reloadDelay: 2000,
    trail: true,
    trailDuration: 1000,
    fireSound: 'railgunshot',
    reloadSound: 'railgunreload3',
    reloadSoundVol: 1.4,
    tracerRate: 1,
    tracerLightColor: 0x2c75ff,
    tracerLightIntensity: 10,
    tracerProjectileColor: 0x2c75ff,
    tracerLightRadius: 150,
    tracerScaleUp: 1,
    tracerHitFadeTime: 2000,
    tracerHitLightRadius: 50,
    tracerHitLightIntensity: 10,
  },
} as WeaponsList

export const enemyWeapons = {
  enemyPlasmaSpit: {
    name: 'enemyPlasmaSpit',
    fireDelay: 10000,
    image: 'bullet1',
    initialSpeed: 400,
    baseSpread: 0.03,
    roundHeight: 20,
    roundWidth: 4,
    maxRange: 900,
    damage: 0,
    explodeRadius: 50,
    explodeDamage: 40,
    explodeSound: 'plasmaboom',
    explodeColor: 0x44ff44,
    explodeSoundVol: 1.5,
    explodeAfterGlowDuration: 1000,
    explodeAfterGlowTint: 0x99ff99,
    explodeAfterGlowIntensity: 10,
    explodeAfterGlowRadius: 150,
    scorchTint: 0x99ff99,
    penetration: 0,
    muzzleFlashSize: 3,
    fireSound: 'alienshot',
    fireSoundVol: 2,
    fireAverageDetune: -200,
    fireDetuneRange: 200,
    tracerRate: 1,
    tracerLightColor: 0x99ff99,
    tracerLightIntensity: 1,
    tracerProjectileColor: 0x99ff99,
    tracerLightRadius: 80,
    tracerScaleUp: 1.5,
    tracerHitFadeTime: 0,
    tracerHitLightRadius: 0,
    tracerHitLightIntensity: 2.5,
    trail: true,
    trailDuration: 100,
    trailTint: 0xaaffaa,
  },
} as EnemyWeaponsList
